/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { CardModule } from '@radzen/angular/dist/card';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { SidebarToggleModule } from '@radzen/angular/dist/sidebar-toggle';
import { LabelModule } from '@radzen/angular/dist/label';
import { ProfileMenuModule } from '@radzen/angular/dist/profilemenu';
import { GravatarModule } from '@radzen/angular/dist/gravatar';
import { SidebarModule } from '@radzen/angular/dist/sidebar';
import { PanelMenuModule } from '@radzen/angular/dist/panelmenu';
import { FooterModule } from '@radzen/angular/dist/footer';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { LoginModule } from '@radzen/angular/dist/login';
import { GridModule } from '@radzen/angular/dist/grid';
import { FormModule } from '@radzen/angular/dist/form';
import { HtmlModule } from '@radzen/angular/dist/html';
import { ButtonModule } from '@radzen/angular/dist/button';
import { TabsModule } from '@radzen/angular/dist/tabs';
import { TemplateFormModule } from '@radzen/angular/dist/template-form';
import { DropDownDataGridModule } from '@radzen/angular/dist/dropdown-datagrid';
import { RequiredValidatorModule } from '@radzen/angular/dist/required-validator';
import { DatePickerModule } from '@radzen/angular/dist/datepicker';
import { DropDownModule } from '@radzen/angular/dist/dropdown';
import { NumericModule } from '@radzen/angular/dist/numeric';
import { TextBoxModule } from '@radzen/angular/dist/textbox';
import { TextAreaModule } from '@radzen/angular/dist/textarea';
import { SSRSViewerModule } from '@radzen/angular/dist/ssrsviewer';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { AcessoComponent } from './acesso/acesso.component';
import { ApplicationRolesComponent } from './application-roles/application-roles.component';
import { CadastrarUsuarioComponent } from './cadastrar-usuário/cadastrar-usuário.component';
import { AddApplicationRoleComponent } from './add-application-role/add-application-role.component';
import { ApplicationUsersComponent } from './application-users/application-users.component';
import { EditarUsuarioComponent } from './editar-usuário/editar-usuário.component';
import { ProfileComponent } from './profile/profile.component';
import { UnauthorizedComponent } from './unauthorized/unauthorized.component';
import { ReunioesComponent } from './reunioes/reunioes.component';
import { AddReunioComponent } from './add-reunio/add-reunio.component';
import { EditReunioComponent } from './edit-reunio/edit-reunio.component';
import { ParticipantesComponent } from './participantes/participantes.component';
import { AddParticipanteComponent } from './add-participante/add-participante.component';
import { EditParticipanteComponent } from './edit-participante/edit-participante.component';
import { AddPassagemComponent } from './add-passagem/add-passagem.component';
import { ReembolsosDespesasComponent } from './reembolsos-despesas/reembolsos-despesas.component';
import { AddReembolsosDespesaComponent } from './add-reembolsos-despesa/add-reembolsos-despesa.component';
import { EditReembolsosDespesaComponent } from './edit-reembolsos-despesa/edit-reembolsos-despesa.component';
import { ItensReembolsosDespesasComponent } from './itens-reembolsos-despesas/itens-reembolsos-despesas.component';
import { AddItensReembolsosDespesaComponent } from './add-itens-reembolsos-despesa/add-itens-reembolsos-despesa.component';
import { EditItensReembolsosDespesaComponent } from './edit-itens-reembolsos-despesa/edit-itens-reembolsos-despesa.component';
import { ComprovantesComponent } from './comprovantes/comprovantes.component';
import { AddComprovanteComponent } from './add-comprovante/add-comprovante.component';
import { EditComprovanteComponent } from './edit-comprovante/edit-comprovante.component';
import { EditPendenciasComponent } from './edit-pendencias/edit-pendencias.component';
import { RelatorioReembolsoComponent } from './relatorio-reembolso/relatorio-reembolso.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';

import { PnldService } from './pnld.service';
import { SecurityService, UserService } from './security.service';
import { SecurityInterceptor } from './security.interceptor';
import { AuthGuard } from './auth.guard';

export const PageDeclarations = [
  AcessoComponent,
  ApplicationRolesComponent,
  CadastrarUsuarioComponent,
  AddApplicationRoleComponent,
  ApplicationUsersComponent,
  EditarUsuarioComponent,
  ProfileComponent,
  UnauthorizedComponent,
  ReunioesComponent,
  AddReunioComponent,
  EditReunioComponent,
  ParticipantesComponent,
  AddParticipanteComponent,
  EditParticipanteComponent,
  AddPassagemComponent,
  ReembolsosDespesasComponent,
  AddReembolsosDespesaComponent,
  EditReembolsosDespesaComponent,
  ItensReembolsosDespesasComponent,
  AddItensReembolsosDespesaComponent,
  EditItensReembolsosDespesaComponent,
  ComprovantesComponent,
  AddComprovanteComponent,
  EditComprovanteComponent,
  EditPendenciasComponent,
  RelatorioReembolsoComponent,
];

export const LayoutDeclarations = [
  LoginLayoutComponent,
  MainLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  PnldService,
  UserService,
  SecurityService,
  {
    provide: HTTP_INTERCEPTORS,
    useClass: SecurityInterceptor,
    multi: true
  },
  AuthGuard,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  CardModule,
  ContentContainerModule,
  HeaderModule,
  SidebarToggleModule,
  LabelModule,
  ProfileMenuModule,
  GravatarModule,
  SidebarModule,
  PanelMenuModule,
  FooterModule,
  ContentModule,
  HeadingModule,
  LoginModule,
  GridModule,
  FormModule,
  HtmlModule,
  ButtonModule,
  TabsModule,
  TemplateFormModule,
  DropDownDataGridModule,
  RequiredValidatorModule,
  DatePickerModule,
  DropDownModule,
  NumericModule,
  TextBoxModule,
  TextAreaModule,
  SSRSViewerModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
