/*
  This file is automatically generated. Any changes will be overwritten.
  Modify add-itens-reembolsos-despesa.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs/Subscription';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { NumericComponent } from '@radzen/angular/dist/numeric';
import { ButtonComponent } from '@radzen/angular/dist/button';

import { PnldService } from '../pnld.service';
import { SecurityService } from '../security.service';

export class AddItensReembolsosDespesaGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: TemplateFormComponent;
  @ViewChild('label1') label1: LabelComponent;
  @ViewChild('ReembolsoDespesa') reembolsoDespesa: DropDownComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('Tipo') tipo: DropDownComponent;
  @ViewChild('TipoRequiredValidator') tipoRequiredValidator: RequiredValidatorComponent;
  @ViewChild('label3') label3: LabelComponent;
  @ViewChild('Data') data: DatePickerComponent;
  @ViewChild('DataRequiredValidator') dataRequiredValidator: RequiredValidatorComponent;
  @ViewChild('label4') label4: LabelComponent;
  @ViewChild('Origem') origem: TextBoxComponent;
  @ViewChild('label5') label5: LabelComponent;
  @ViewChild('Destino') destino: TextBoxComponent;
  @ViewChild('label6') label6: LabelComponent;
  @ViewChild('Entrada') entrada: DatePickerComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('Saida') saida: DatePickerComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('Referencia') referencia: TextBoxComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('Empresa') empresa: TextBoxComponent;
  @ViewChild('label10') label10: LabelComponent;
  @ViewChild('ValorGasto') valorGasto: NumericComponent;
  @ViewChild('label11') label11: LabelComponent;
  @ViewChild('ValorConcedido') valorConcedido: NumericComponent;
  @ViewChild('button1') button1: ButtonComponent;
  @ViewChild('button2') button2: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  pnld: PnldService;

  security: SecurityService;

  getReembolsosDespesasPageSize: any;

  getReembolsosDespesasResult: any;

  getReembolsosDespesasCount: any;

  getTiposItensReembolsosDespesasPageSize: any;

  getTiposItensReembolsosDespesasResult: any;

  getTiposItensReembolsosDespesasCount: any;

  formData: any;

  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.pnld = this.injector.get(PnldService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.getReembolsosDespesasPageSize = 10;

    this.pnld.getReembolsosDespesas(null, this.getReembolsosDespesasPageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getReembolsosDespesasResult = result.value;

      this.getReembolsosDespesasCount = result['@odata.count'];
    }, (result: any) => {

    });

    this.getTiposItensReembolsosDespesasPageSize = 10;

    this.pnld.getTiposItensReembolsosDespesas(null, this.getTiposItensReembolsosDespesasPageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getTiposItensReembolsosDespesasResult = result.value;

      this.getTiposItensReembolsosDespesasCount = result['@odata.count'];
    }, (result: any) => {

    });

    this.formData = {};
  }

  form0Submit(event: any) {
    this.pnld.createItensReembolsosDespesa(event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      }
      this.router.navigate(['edit-reembolsos-despesa']);
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to create new ItensReembolsosDespesa!` });
    });
  }

  TipoChange(event: any) {
    
  }

  button2Click(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }
}
